DROP TABLE person;

DROP TABLE pet;

CREATE TABLE IF NOT EXISTS person
(
    person_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    has_license BOOLEAN DEFAULT 'false',
    car_id      BIGINT,
    CONSTRAINT person PRIMARY KEY (person_id)
    );

CREATE TABLE IF NOT EXISTS pet
(
    pet_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    breed  VARCHAR(255),
    age   NUMERIC(16, 2),
    CONSTRAINT pet PRIMARY KEY (pet_id)
    );

ALTER TABLE person
    ADD CONSTRAINT fk_person_on_pet FOREIGN KEY (pet_id) REFERENCES pet
        ON DELETE SET NULL;

--- test

INSERT INTO pet (name, breed, age)
VALUES ('A', 'A1', 100.0);

INSERT INTO person (name, pet_id)
VALUES ('Will', 1);

delete
from pet
where pet_id = 1;